development:
   adapter: postgresql # replace with remote db type if different
   encoding: utf8 # modify if it is different
   reconnect: false
   database: postgres_0siq # remote database name
   pool: 5
   username: postgres_0siq_user # username for remote database
   password: cfUVqbOL7eRSfMFFBWR7xxZfgpD2MJNp  # password for remote database
   host: dpg-cjbpn9k5kgrc73f6mcs0-a.oregon-postgres.render.com # this will be host where database is installed
production:
   adapter: postgresql # replace with remote db type if different
   encoding: utf8 # modify if it is different
   reconnect: false
   database: postgres_0siq # remote database name
   pool: 5
   username: postgres_0siq_user # username for remote database
   password: cfUVqbOL7eRSfMFFBWR7xxZfgpD2MJNp  # password for remote database
   host: dpg-cjbpn9k5kgrc73f6mcs0-a.oregon-postgres.render.com # this will be host where database is installed
test:
   adapter: postgresql # replace with remote db type if different
   encoding: utf8 # modify if it is different
   reconnect: false
   database: postgres_0siq # remote database name
   pool: 5
   username: postgres_0siq_user # username for remote database
   password: cfUVqbOL7eRSfMFFBWR7xxZfgpD2MJNp  # password for remote database
   host: dpg-cjbpn9k5kgrc73f6mcs0-a.oregon-postgres.render.com # this will be host where database is installed

